Repository bifrost-platform/bifrost-node, pull requests merged in 2023-10, with the labels that each got.

#26 NODE-64, chores: add systemd configuration examples
  deploy/mainnet/bifrost-node.service.endpoint.example
  deploy/mainnet/bifrost-node.service.validator.example
  deploy/testnet/bifrost-node.service.endpoint.example
  deploy/testnet/bifrost-node.service.validator.example
Labels: chore

#27 fix: resolve balance inconsistency
  Cargo.lock
  Cargo.toml
  pallets/bfc-offences/Cargo.toml
  pallets/bfc-offences/src/lib.rs
  pallets/bfc-offences/src/pallet/mod.rs
  pallets/bfc-staking/Cargo.toml
  pallets/bfc-staking/src/lib.rs
  pallets/bfc-staking/src/pallet/mod.rs
  pallets/bfc-utility/Cargo.toml
  pallets/bfc-utility/src/lib.rs
  pallets/relay-manager/Cargo.toml
  pallets/relay-manager/src/lib.rs
  pallets/relay-manager/src/pallet/mod.rs
  precompiles/bfc-offences/Cargo.toml
  precompiles/bfc-staking/Cargo.toml
  precompiles/collective/Cargo.toml
  precompiles/governance/Cargo.toml
  precompiles/relay-manager/Cargo.toml
  rust-toolchain
  rust-toolchain.toml
Labels: bug

#28 Resolve CVE-2023-38497
  rust-toolchain.toml
Labels: bug, dependencies
