Repository bifrost-platform/bifrost-node, pull requests merged in 2024-01, with the labels that each got.

#35 NODE-86, deps: patch rust-evm
  Cargo.lock
  Cargo.toml
  runtime/dev/src/lib.rs
  runtime/mainnet/src/lib.rs
  runtime/testnet/src/lib.rs
Labels: bug, do not merge, dependencies

#37 NODE-84, chore: web3_clientVersion response format
  Cargo.lock
  node/common/src/rpc.rs
  node/core/src/command.rs
  node/dev/src/rpc.rs
  node/dev/src/service.rs
  node/mainnet/src/rpc.rs
  node/mainnet/src/service.rs
  node/testnet/src/rpc.rs
  node/testnet/src/service.rs
  tests/package-lock.json
Labels: chore

#38 NODE-78, fix: delayed relayer address update
  Cargo.lock
  pallets/bfc-staking/src/pallet/impls.rs
  pallets/bfc-staking/src/pallet/mod.rs
  pallets/relay-manager/src/lib.rs
  pallets/relay-manager/src/pallet/impls.rs
  pallets/relay-manager/src/pallet/mod.rs
  pallets/relay-manager/src/weights.rs
  primitives/bfc-staking/src/traits.rs
  tests/tests/pallets/test_bfc_staking.ts
  tests/tests/pallets/test_relay_manager.ts
Labels: bug
