Repository bifrost-platform/bifrost-node, pull requests merged in 2024-09, with the labels that each got.

#76 NODE-131, fix: add verifiers to signature
  pallets/btc-registration-pool/src/lib.rs
  pallets/btc-registration-pool/src/pallet/impls.rs
  pallets/btc-registration-pool/src/pallet/mod.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  runtime/dev/src/lib.rs
Labels: bug

#77 NODE-128, fix: use correct service state check
  pallets/btc-registration-pool/src/pallet/mod.rs
  runtime/dev/src/lib.rs
Labels: bug

#78 NODE-134, feat: add `submit_bump_fee_request()`
  pallets/btc-socket-queue/src/pallet/impls.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
Labels: enhancement

#80 NODE-135, fix: estimate size of finalized psbt's tx for fee verification
  pallets/btc-socket-queue/src/pallet/impls.rs
Labels: bug

#82 NODE-137, fix: add missing #[precompile::view] macro
  precompiles/btc-registration-pool/src/lib.rs
Labels: chore

#83 NODE-138, fix: use `ensure_root()` and remove `SetOrigin`
  pallets/btc-socket-queue/src/pallet/mod.rs
  runtime/dev/src/lib.rs
  runtime/testnet/src/lib.rs
Labels: chore

#84 NODE-139, fix: only permit when the migration tx broadcast
  pallets/btc-registration-pool/src/pallet/impls.rs
  pallets/btc-registration-pool/src/pallet/mod.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  primitives/multi-sig/src/traits.rs
Labels: chore

#86 NODE-141, fix: include field `is_approved` into signature message
  pallets/btc-socket-queue/src/pallet/mod.rs
Labels: bug

#85 NODE-140, fix: `btc-socket-queue` should be empty before pool migration
  pallets/btc-registration-pool/src/pallet/mod.rs
  pallets/btc-socket-queue/src/pallet/impls.rs
  primitives/multi-sig/src/traits.rs
  runtime/dev/src/lib.rs
  runtime/testnet/src/lib.rs
Labels: bug

#87 NODE-142, refactor: apply pending and approval process when setting refunds
  pallets/btc-registration-pool/src/lib.rs
  pallets/btc-registration-pool/src/pallet/impls.rs
  pallets/btc-registration-pool/src/pallet/mod.rs
  pallets/btc-socket-queue/src/pallet/impls.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  precompiles/btc-registration-pool/src/interface.sol
  precompiles/btc-registration-pool/src/lib.rs
  primitives/multi-sig/src/traits.rs
Labels: bug
