Repository bifrost-platform/bifrost-node, pull requests merged in 2024-06, with the labels that each got.

#54 NODE-117, feat: rollback protocol
  Cargo.lock
  pallets/btc-registration-pool/src/pallet/impls.rs
  pallets/btc-socket-queue/Cargo.toml
  pallets/btc-socket-queue/src/lib.rs
  pallets/btc-socket-queue/src/pallet/impls.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  pallets/btc-socket-queue/src/weights.rs
  pallets/relay-manager/src/pallet/impls.rs
  precompiles/btc-socket-queue/src/interface.sol
  precompiles/btc-socket-queue/src/lib.rs
  precompiles/btc-socket-queue/src/types.rs
  primitives/bfc-staking/src/traits.rs
  primitives/multi-sig/src/lib.rs
  primitives/multi-sig/src/traits.rs
  runtime/dev/src/lib.rs
  tests/constants/demo_contract.ts
  tests/tests/pallets/test_btc_socket_queue.ts
Labels: enhancement

#55 [CCCP-385] registration-pool migration process
  Cargo.lock
  pallets/btc-registration-pool/src/lib.rs
  pallets/btc-registration-pool/src/migrations.rs
  pallets/btc-registration-pool/src/pallet/impls.rs
  pallets/btc-registration-pool/src/pallet/mod.rs
  pallets/btc-registration-pool/src/weights.rs
  pallets/btc-socket-queue/Cargo.toml
  pallets/btc-socket-queue/src/lib.rs
  pallets/btc-socket-queue/src/pallet/impls.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  pallets/btc-socket-queue/src/weights.rs
  pallets/relay-manager/src/pallet/impls.rs
  precompiles/btc-registration-pool/src/interface.sol
  precompiles/btc-registration-pool/src/lib.rs
  precompiles/btc-socket-queue/src/interface.sol
  precompiles/btc-socket-queue/src/lib.rs
  precompiles/btc-socket-queue/src/types.rs
  primitives/bfc-staking/src/traits.rs
  primitives/multi-sig/src/lib.rs
  primitives/multi-sig/src/traits.rs
  runtime/dev/src/lib.rs
  tests/constants/demo_contract.ts
  tests/tests/pallets/test_btc_socket_queue.ts
Labels: enhancement

#56 NODE-119, unsigned psbt message update
  pallets/btc-registration-pool/src/pallet/impls.rs
  pallets/btc-socket-queue/src/lib.rs
  pallets/btc-socket-queue/src/pallet/impls.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  pallets/btc-socket-queue/src/weights.rs
  primitives/multi-sig/src/traits.rs
Labels: bug

#57 minor fixes
  Dockerfile
  pallets/btc-registration-pool/src/pallet/mod.rs
  pallets/btc-socket-queue/src/pallet/impls.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  runtime/dev/src/lib.rs
Labels: enhancement

#59 chore: update ensure
  pallets/btc-socket-queue/src/pallet/mod.rs
Labels: bug

#60 fix: socket queue minor update
  pallets/btc-socket-queue/src/pallet/impls.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  runtime/dev/src/lib.rs
Labels: bug

#61 fix: update access control
  pallets/btc-registration-pool/src/pallet/mod.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  runtime/dev/src/lib.rs
Labels: chore

#62 fix: simply use txid instead of psbt bytes
  pallets/btc-socket-queue/src/lib.rs
  pallets/btc-socket-queue/src/pallet/mod.rs
  runtime/dev/src/lib.rs
Labels: chore
